---
output: github_document
---

<!-- Este .md fue generado a partir del .Rmd homónimo. Edítese el .Rmd -->


# RStudio, notificaciones por GitHub, *issues*

La mejor manera de confirmar que has leído y saben usar la guía [Cómo hacer una asignación](https://github.com/maestria-geotel-master/material-de-apoyo/blob/master/ref/como-hacer-una-asignacion.md), es precisamente solicitándote hacer una asignación en la que sigas los pasos explicados. *Vamo' al mambo*

## ¿Qué necesitarás?

* PC con conexión a internet. 
* Guía [Cómo hacer una asignación](https://github.com/maestria-geotel-master/material-de-apoyo/blob/master/ref/como-hacer-una-asignacion.md). Manten la guía en pantalla para posteriores consultas. Puedes organizar lateralmente la asignación y la guía para tenerlas ambas visibles. En caso contrario, recuerda que la combinación de teclas `ALT+TAB` intercambia ventanas (...de nada).
* RStudio Desktop instalado en tu PC, o RStudio desde el servidor habilitado por el profesor.

## Realiza una asignación con RStudio

En la guía, ve a la sección **Realiza tu asignación**, subsección [**Usando RStudio**](https://github.com/maestria-geotel-master/material-de-apoyo/blob/master/ref/como-hacer-una-asignacion.md#usando-rstudio). Sigue los pasos para hacer lo siguiente:

1. Abre RStudio.
2. Clona este mismo repo que probablemente estarás leyendo desde GitHub.
3. Abre este documento `README.md`. **Recuerda, abre el que termina en `.md`, no el otro que se le parece mucho**.
4. En la consola de R, escribe el siguiente código `sample(1:1000, 5)` (cópialo y pégalo en la consola) y presiona la tecla `<enter>`
5. Copia el resultado de la consola y pégalo en este documento, justo dentro de las siguientes tildes diacríticas (borra los puntos suspensivos pero no las comillas): ` ... `
6. Ve a la pestaña Git y crea el `Commit` (sigue la guía).
7. Luego haz `Push` (sigue la guía).
8. Verifica que los cambios se actualizaron en el repo de GitHub.

## Notifícame que has terminado

En la guía, ve a la sección [**Notifícame que has terminado**](https://github.com/maestria-geotel-master/material-de-apoyo/blob/master/ref/como-hacer-una-asignacion.md#notif%C3%ADcame-que-has-terminado). Sigue los pasos que allí se indican para hacer lo siguiente:

1. Abre la interfaz web de GitHub y localiza el repo de esta asignación. 
2. Notifícame que has terminado de hacer esta asignación con el mensaje que prefieras (se vale descargar la ira en este momento), sin olvidar hacerme mención (sigue la guía).
   
## Crea un *issue*

En la guía, ve a la sección [**Pide ayuda creando un *issue* o incidencia**](https://github.com/maestria-geotel-master/material-de-apoyo/blob/master/ref/como-hacer-una-asignacion.md#pide-ayuda-creando-un-issue-o-incidencia). Sigue los pasos para hacer lo siguiente:

1. Crea un *issue*.
2. Ponle por título `Hola issues`, o lo que se te antoje.
3. Plantea una incidencia, hipotética o real, que hayas tenido al ejecutar esta asignación, y/o pide ayuda (aquí también se vale descargar la ira, con código reproducible lógicamente). Los *issues* se crean dentro de un repo, y esta asignación es un repo. Por lo tanto, en casos reales, los *issues* tratan cuestiones relacionadas al repo en cuestión. Utiliza siempre el repo que corresponda al *issue* que quieras plantear.
4. Tan pronto presiones `Submit new issue` me llegará una notificación por correo electrónico. Yo "intentaré" ayudar y, si el repo es público, cualquiera de los/as miembros de la asignatura también podrá hacerlo.
